services:
  postgres:
    container_name: vacancies_postgres
    image: postgres:15
    environment:
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASS}
      POSTGRES_DB: ${TEST_DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
#    platform: linux/amd64
    ports:
      - "5434:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5

  vacancies_service:
    container_name: vacancies_service
    build:
      context: .
#    platform: linux/amd64
    ports:
      - "8005:8005"
    command: uvicorn src.main:app --host 0.0.0.0 --port 8005
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: